before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-head
  - jruby-19mode
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
