rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
  # - 2.2.0
  # - 2.2.5
  # - 2.3.0
  # - 2.3.1
  - ruby-head
  - jruby-19mode
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
